server:
    port: 8082
spring:
    kafka:
        bootstrap-servers: kafka:19092
        properties:
            schema.registry.url: http://schema-registry:8081
            specific.avro.reader: true
        consumer:
            group-id: group_id
            auto-offset-reset: earliest
            #properties:
                #specific.avro.reader: true
                #default.key.serde: org.apache.kafka.common.serialization.Serdes.StringSerde
                #default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                #            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                #            value-deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer